### ISSUE TITLE
Unable to install with composer

### ISSUE THREAD

**Issue by bkno** [syntaxera/cakephp-sparkpost-plugin#1]
Hi,

When I run `composer require syntaxera/cakephp-sparkpost-plugin` it says "could not find package".

Submitting it to Packagist should fix this: https://packagist.org/packages/submit

**Comment by robojamison** [comment]
Fixed, however Composer throws a ton of publickey warnings when installing. Looking into those now.

**Comment by bkno** [comment]
Thanks, it's installing fine for me now.
