### ISSUE TITLE
Unable to find lower version cakephp sparkpost code.

### ISSUE THREAD

**Issue by chinmay235** [syntaxera/cakephp-sparkpost-plugin#20]
I have an old project. Client need to implement SparkPost email.  I want to SparkPost code in cakephp 2.x version. Please help me...

**Comment by robojamison** [comment]
This plugin only supports the 3.x branch of CakePHP, and there are no plans to support 2.x at this time. 3.x was released in March 2015 and is superior in many ways to 2.x, which was why it was chosen as the platform for this plugin.

If you would like to attempt to implement a 2.x solution, you are certainly welcome to. I suggest you consult the [Sparkpost PHP API docs](https://github.com/SparkPost/php-sparkpost) and the [CakePHP 2.x email documentation](http://book.cakephp.org/2.0/en/core-utility-libraries/email.html#creating-custom-transports), specifically the section involving creating custom transports.

**Comment by chinmay235** [comment]
You are right. But this code also same. I tried to modify that code. Because my php version 5.3 so namespace and using alias not working for SparkPost code.

**Comment by robojamison** [comment]
PHP 5.3.0 supports namespaces, but lower versions of CakePHP 2.x do not. You will have to write a custom classloader. Mark has a [good article on this topic](http://www.dereuromark.de/2012/08/06/namespaces-in-vendor-files-and-cake2-x/) on his blog. Keep in mind the namespace path used in a CakePHP 3.x plugin will not be the same as the namespace path used in a CakePHP 2.x plugin.

**Comment by chinmay235** [comment]
@robojamison  I will try this way.

Thank a lot. 

@chinmay235
