### ISSUE TITLE
abandoned dependencies package

### ISSUE THREAD

**Issue by anhtuank7c** [syntaxera/cakephp-sparkpost-plugin#21]
```
Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.
Package sparkpost/php-sparkpost is abandoned, you should avoid using it. Use sparkpost/sparkpost instead.
```

**Comment by robojamison** [comment]
Use the `develop` branch, the dependency on the outdated package(s) has been removed there. It used to be that using the outdated packages was required to work with the SparkPost PHP library. I'll check to see if the dev branch is stable and merge it into master soon.
