### ISSUE TITLE
Nice idea, but maybe a Transport

### ISSUE THREAD

**Issue by dereuromark** [syntaxera/cakephp-sparkpost-plugin#3]
As a component this is a bit too limited to the controller scope IMO
If you provided this as Email Transport class, this would be easily configurable without changing any code and it would be available in all layers, also from CLI (if you, and you should, use Queue plugins etc to send asynch emails or talk to APIs one-way) or model layer.

**Comment by robojamison** [comment]
You're totally right, I actually feel a tad silly for not doing this until now. I'm going to branch off and develop this as a transport instead (or in addition to) the component. Thanks!
