### ISSUE TITLE
Define CakePHP Dependency in Comopser

### ISSUE THREAD

**Issue by ravage84** [syntaxera/cakephp-sparkpost-plugin#7]
Hi

Even though I currently don't have a need for your plugin, it seems very interesting.
Thus, I want to give you some hints how to improve your package.

It seems you don't define your CakePHP dependency in your ``composer.json``.
You could do it like this:
https://github.com/FriendsOfCake/crud/blob/v4.0.0/composer.json#L43

Greetings from Switzerland.

**Comment by robojamison** [comment]
Does this have some technical purpose, or is it purely semantic? E.g. is the purpose of adding CakePHP x.y as a dependency purely to indicate that it only _supports_ CakePHP x.y, or is there another reason?

**Comment by ravage84** [comment]
Besides the informational benefit of getting the dependency shown on packagist (https://packagist.org/packages/syntaxera/cakephp-sparkpost-plugin), you also prevent people having the wrong version of CakePHP installed (through Composer) from installing your plugin.

**Comment by robojamison** [comment]
OK, I'll do that. Thanks for the pointer. Thanks for all the pointers, actually, I'm making an action plan to deal with all of them one-by-one.

**Comment by ravage84** [comment]
You are very welcome. Thank you for sharing your work with us. One day I might need it :smile_cat:
